development:
  adapter: postgresql
  encoding: unicode
  database: bike_commute_challenge_development
  host: localhost
  pool: 5
  username: bike_commute_challenge
  password: peddlehard

test:
  adapter: postgresql
  encoding: unicode
  database: bike_commute_challenge_test
  host: localhost
  pool: 5
  username: bike_commute_challenge
  password: peddlehard
